- id: '1599574905538'
  alias: New Automation
  description: ''
  trigger:
  - device_id: 330e8e5c8ff24cd693ea8590cae49204
    domain: binary_sensor
    entity_id: binary_sensor.door_window_sensor_158d00041bc65d
    platform: device
    type: opened
  condition: []
  action:
  - brightness_pct: 100
    device_id: 17a5055a7fba48d2b6800c0ec90fbccb
    domain: light
    entity_id: light.gateway_light_286c0788bafc
    type: turn_on
  mode: single
- id: '1599574976501'
  alias: New Automation
  description: ''
  trigger:
  - device_id: 330e8e5c8ff24cd693ea8590cae49204
    domain: binary_sensor
    entity_id: binary_sensor.door_window_sensor_158d00041bc65d
    platform: device
    type: opened
  condition: []
  action:
  - brightness_pct: 100
    device_id: 17a5055a7fba48d2b6800c0ec90fbccb
    domain: light
    entity_id: light.gateway_light_286c0788bafc
    type: turn_on
  mode: single
