title: Мой Дом (ihome)

resources:
  - url: /local/community/text-divider-row/text-divider-row.js
    type: module
  - url: /local/community/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /local/community/lovelace-card-mod/card-mod.js
    type: module
  - url: /local/community/vacuum-card/vacuum-card.js
    type: module
  - url: /local/community/button-card/button-card.js
    type: module
  - url: /local/community/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
    type: module
  - url: /local/community/simple-thermostat/simple-thermostat.js
    type: module

views:
####################################################
#                                                  #
#                   Sensors Page                   #
#                                                  #
####################################################
  - title: Sensors
    icon: mdi:camera
    cards:
      - type: vertical-stack
        cards:
        - type: markdown
          content: >
            **Doors**
        - type: entities
          entities:
          - binary_sensor.door_window_sensor_158d00041bc65d
        - type: markdown
          content: >
            **Water**
        - type: entities
          entities:
          - binary_sensor.water_leak_sensor_158d00045ad2e1
          - switch.tuya_smart_valve
          # - switch.62531570a4cf12e5b139
        - type: markdown
          content: >
            **Motion**
        - type: entities
          entities:
          - binary_sensor.motion_sensor_158d0003f4c4c1

####################################################
#                                                  #
#                   Sensors Page                   #
#                                                  #
####################################################
  - title: Beok Control
    icon: mdi:home-thermometer-outline
    cards:
      # - type: vertical-stack
      #   cards:
      #   - type: markdown
      #     content: >
      #       **Beok Home**
      #   - type: entities
      #     entities:
      #     - switch.kitchen_thermal_control
      - type: 'custom:simple-thermostat'
        entity: climate.kitchen_thermal_control_climate
        step_size: 1
        sensors:
          # - entity: sensor.fibaro_system_fgwpef_wall_plug_gen5_energy
          # - entity: sensor.fibaro_system_fgwpef_wall_plug_gen5_power
            # name: Energy today
          - attribute: min_temp
            name: Min temp
        control:
          hvac:
            some_mode: false
            another_mode: false
            'off':
              name: Make it cold
              icon: false
            'on':
              name: false
              icon: mdi:whitewalker

####################################################
#                                                  #
#                Server Status Page                #
#                                                  #
####################################################

  - title: Server Status
    icon: mdi:server

    cards:

      - type: vertical-stack
        cards:

        - type: markdown
          content: >
            **Current State**

        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.time
              name: Time
              icon: mdi:clock-outline
            - entity: sensor.date
              name: Date
              icon: mdi:calendar-account-outline

        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.db_size
              name: DB Size
              icon: mdi:database

      - type: vertical-stack
        cards:
        - type: markdown
          content: >
            **Charts**

        - type: horizontal-stack
          cards:
            - type: gauge
              name: CPU Load
              entity: sensor.processor_use
              unit: '%'
              severity:
                green: 0
                yellow: 60
                red: 85
            - type: gauge
              name: Memory Load
              entity: sensor.memory_use_percent
              unit: '%'
              severity:
                green: 0
                yellow: 60
                red: 85
        - type: horizontal-stack
          cards:
            - type: gauge
              name: Storage usage
              entity: sensor.disk_use_percent
              unit: '%'
              severity:
                green: 0
                yellow: 50
                red: 75
            - type: gauge
              name: Free Spase
              entity: sensor.disk_free
              unit: 'Gb'
              severity:
                red: 50
                yellow: 100
                green: 150

####################################################
#                                                  #
#                    Weather Page                  #
#                                                  #
####################################################

  - title: Weather
    icon: mdi:weather-sunny
    cards:
      - type: weather-forecast
        entity: weather.home

####################################################
#                                                  #
#                    Batteries Page                #
#                                                  #
####################################################

  - title: Batteries
    icon: mdi:battery
    cards:
      - type: vertical-stack
        cards:
        - type: markdown
          content: >
            **Charge Level**
        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.battery_158d00045ad2e1
            - entity: sensor.battery_158d00041bc65d
            - entity: sensor.battery_158d0003f4c4c1

####################################################
#                                                  #
#                    Controls Page                 #
#                                                  #
####################################################

  - title: Controls
    icon: mdi:lightbulb
    cards:
      - type: vertical-stack
        cards:
        - type: markdown
          content: >
            **Light**
        - type: entities
          show_header_toggle: false
          entities:
            - entity: light.gateway_light_286c0788bafc
            - entity: sensor.illumination_286c0788bafc
        - type: entities
          show_header_toggle: false
          entities:
            - entity: light.entrance_bulb

#################################################################
#                                                               #
#                 Appliances -  RoboVac Card                    #
#                                                               #
#################################################################

  - title: Controls
    icon: mdi:washing-machine
    cards:
      - type: 'custom:vacuum-card'
        entity: vacuum.robovac
        stats:
          default:
            - attribute: filter_left
              unit: hours
              subtitle: Filter
            - attribute: side_brush_left
              unit: hours
              subtitle: Side brush
            - attribute: main_brush_left
              unit: hours
              subtitle: Main brush
            - attribute: sensor_dirty_left
              unit: hours
              subtitle: Sensors
          cleaning:
            - attribute: cleaned_area
              unit: m2
              subtitle: Cleaning area
            - attribute: cleaning_time
              unit: minutes
              subtitle: Cleaning time

        # actions:
        #   - name: Clean living room
        #     service: script.clean_living_room
        #     icon: 'mdi:sofa'
        #   - name: Clean bedroom
        #     service: script.clean_bedroom
        #     icon: 'mdi:bed-empty'
        #   - name: Clean kitchen
        #     service: script.clean_kitchen
        #     icon: 'mdi:silverware-fork-knife'
      # - type: 'custom:xiaomi-vacuum-map-card'
      #   entity: vacuum.robovac